### PR TITLE
fix trailing zero with non-zero value

### PR DESCRIPTION
**Pull request by TrySound**
First correction.
Add please your .jscsrc for code style clarity.

### CODE REVIEW

**Comment by ben-eb** [comment]
It's there: https://github.com/ben-eb/postcss-convert-values/blob/master/.jshintrc

**Comment by TrySound** [comment]
@ben-eb It's not exact rules. jscs let you rule like 'if ()' or 'if()'

**Comment by TrySound** [comment]
Found! integers with zero tail processes by converter, but percents not converts.

**Comment by TrySound** [comment]
@ben-eb At least this one https://github.com/ck86/main-bower-files/blob/master/.jscsrc
You can customize it with jscs.info/rules.html

**Comment by ben-eb** [comment]
Thanks, I'll have a proper look at this when I have some more time. Code style wise though, your patch is fine. :smile:

**Comment by TrySound** [comment]
@ben-eb It's just a beginning! :)=)

**Pull request merged**
